<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Invoice #{{ $order->order_id }} — Optimum Biomedical</title><script src="https://cdn.tailwindcss.com"></script><style>@page{size:A4;margin:12mm}@media print{body{background:#fff!important}.no-print{display:none!important}.invoice{box-shadow:none!important;margin:0!important;max-width:none!important}}</style></head><body class="bg-slate-100 p-5 text-slate-800 sm:p-8">
<div class="no-print mx-auto mb-4 flex max-w-4xl justify-between"><a href="{{ url('/admin/sales') }}" class="rounded-xl border bg-white px-4 py-2 text-sm font-bold">← New Sale</a><button onclick="window.print()" class="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white">Print Invoice</button></div>
<div class="invoice mx-auto min-h-[1120px] max-w-4xl bg-white p-8 shadow-xl sm:p-10">
<div class="flex items-start justify-between gap-6 border-b-2 border-slate-900 pb-6"><div class="flex gap-4"><div class="grid h-20 w-20 place-items-center overflow-hidden rounded-xl bg-slate-100 text-xl font-black text-indigo-600">@if(!empty($company?->logo))
<img src="{{ filter_var($company->logo, FILTER_VALIDATE_URL) ? $company->logo : (str_starts_with((string) $company->logo, 'uploads/') ? asset($company->logo) : asset('uploads/side_image/' . basename((string) $company->logo))) }}"
     alt="{{ $company->company_name ?? 'Company Logo' }}"
     class="h-full w-full object-contain">
@else
OB
@endif</div><div><h1 class="text-2xl font-black">{{ $company->company_name ?: 'Optimum Biomedical' }}</h1><p class="mt-1 max-w-md text-xs leading-5 text-slate-500">{{ $company->address }}</p><p class="text-xs text-slate-500">{{ $company->phone }} @if($company->email) · {{ $company->email }} @endif</p></div></div><div class="text-right"><div class="text-[10px] font-black uppercase tracking-widest text-slate-400">Invoice No</div><div class="text-2xl font-black">#{{ $order->order_id }}</div><div class="text-xs text-slate-500">{{ $order->created_at?->format('d M Y, h:i A') }}</div></div></div>
<div class="grid grid-cols-1 gap-6 border-b sm:grid-cols-2 border-slate-200 py-6"><div><div class="text-[10px] font-black uppercase tracking-widest text-slate-400">Bill To</div><div class="mt-1 font-black">{{ $order->customer_name ?: 'Walk-in Customer' }}</div><div class="text-xs text-slate-500">{{ $order->address }}</div><div class="text-xs text-slate-500">{{ $order->phone }}</div><div class="text-xs text-slate-500">{{ $order->email }}</div></div><div class="text-right"><div class="text-[10px] font-black uppercase tracking-widest text-slate-400">Payment</div><div class="mt-1 font-bold">{{ $order->payment_method }}</div><div class="text-xs font-bold {{ $order->payment_status==='Paid'?'text-emerald-600':'text-amber-600' }}">{{ $order->payment_status }}</div></div></div>
<div class="mt-6 overflow-x-auto"><table class="min-w-[620px] w-full text-sm"><thead><tr class="border-y border-slate-300 bg-slate-50 text-[10px] font-black uppercase tracking-wider"><th class="p-3 text-left">#</th><th class="p-3 text-left">Description</th><th class="p-3 text-center">Qty</th><th class="p-3 text-right">Unit Price</th><th class="p-3 text-right">Discount</th><th class="p-3 text-right">Total</th></tr></thead><tbody class="divide-y divide-slate-100">@php($subtotal=0)@foreach($order->items as $i=>$item)@php($gross=(float)$item->price*(int)$item->qty)@php($line=(float)$item->total)@php($itemDiscount=max(0,$gross-$line))@php($subtotal+=$gross)<tr><td class="p-3">{{ $i+1 }}</td><td class="p-3 font-semibold">{{ $item->product_name }}</td><td class="p-3 text-center">{{ $item->qty }}</td><td class="p-3 text-right">৳ {{ number_format($item->price,2) }}</td><td class="p-3 text-right">৳ {{ number_format($itemDiscount,2) }}</td><td class="p-3 text-right font-bold">৳ {{ number_format($line,2) }}</td></tr>@endforeach</tbody><tfoot class="font-bold"><tr><td colspan="4"></td><td class="p-2 text-right text-slate-500">Sub Total</td><td class="p-2 text-right">৳ {{ number_format($subtotal,2) }}</td></tr><tr><td colspan="4"></td><td class="p-2 text-right text-slate-500">Total Discount</td><td class="p-2 text-right">৳ {{ number_format(max(0,$subtotal-(float)$order->total_amount),2) }}</td></tr><tr class="border-t-2 border-slate-900 text-base"><td colspan="4"></td><td class="p-2 text-right">Grand Total</td><td class="p-2 text-right">৳ {{ number_format($order->total_amount,2) }}</td></tr><tr><td colspan="4"></td><td class="p-2 text-right text-slate-500">Paid</td><td class="p-2 text-right">৳ {{ $order->payment_status==='Paid'?number_format($order->total_amount,2):'0.00' }}</td></tr><tr><td colspan="4"></td><td class="p-2 text-right text-slate-500">Due</td><td class="p-2 text-right">৳ {{ $order->payment_status==='Paid'?'0.00':number_format($order->total_amount,2) }}</td></tr></tfoot></table></div>
<div class="mt-8 text-sm font-bold">In Words: {{ number_format($order->total_amount,2) }} Taka Only</div><div class="mt-20 grid grid-cols-1 gap-8 sm:mt-28 sm:grid-cols-3 sm:gap-10 text-center text-xs font-bold text-slate-500"><div class="border-t border-slate-400 pt-2">For Customer</div><div class="border-t border-slate-400 pt-2">Prepared By</div><div class="border-t border-slate-400 pt-2">For Authority</div></div></div></body></html>
