<?php $__env->startSection('content'); ?>
<div class="mx-auto max-w-5xl space-y-5">
    <div><p class="text-sm font-black uppercase tracking-widest text-indigo-600">Security / Users</p><h1 class="text-3xl font-black"><?php echo e($user ? 'Edit User' : 'Create User'); ?></h1></div>
    <form method="POST" action="<?php echo e($user ? route('admin.users.update',$user) : route('admin.users.store')); ?>" class="space-y-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
        <?php echo csrf_field(); ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($user): ?> <?php echo method_field('PUT'); ?> <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        <div class="grid gap-5 sm:grid-cols-2">
            <label><span class="mb-1.5 block text-sm font-bold">Full name</span><input name="name" value="<?php echo e(old('name',$user->name??'')); ?>" required class="w-full rounded-xl border px-4 py-3"></label>
            <label><span class="mb-1.5 block text-sm font-bold">Phone / Login ID</span><input name="phone" value="<?php echo e(old('phone',$user->phone??'')); ?>" required class="w-full rounded-xl border px-4 py-3"></label>
            <label><span class="mb-1.5 block text-sm font-bold">Password <?php echo e($user?'(leave blank to keep current)':''); ?></span><input type="password" name="password" class="w-full rounded-xl border px-4 py-3" <?php echo e($user?'':'required'); ?>></label>
            <label><span class="mb-1.5 block text-sm font-bold">Confirm password</span><input type="password" name="password_confirmation" class="w-full rounded-xl border px-4 py-3" <?php echo e($user?'':'required'); ?>></label>
            <label><span class="mb-1.5 block text-sm font-bold">Status</span><select name="status" class="w-full rounded-xl border px-4 py-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['active','inactive','blocked']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($status); ?>" <?php if(old('status',$user->status??'active')===$status): echo 'selected'; endif; ?>><?php echo e(ucfirst($status)); ?></option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></label>
        </div>
        <label class="flex items-center gap-3 rounded-2xl bg-amber-50 p-4"><input type="checkbox" name="force_password_change" value="1" <?php if(old('force_password_change',$user->force_password_change??false)): echo 'checked'; endif; ?> class="h-5 w-5 rounded"><span><strong class="block">Force password change</strong><small class="text-slate-600">User must change the password after login.</small></span></label>
        <div><div class="mb-3 flex items-center justify-between"><h2 class="text-lg font-black">Roles</h2><span class="text-xs text-slate-500">Permissions are inherited from selected roles.</span></div><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $roles; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $role): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><label class="flex cursor-pointer items-start gap-3 rounded-2xl border border-slate-200 p-4 hover:border-indigo-300"><input type="checkbox" name="roles[]" value="<?php echo e($role->id); ?>" <?php if(in_array($role->id,old('roles',$user?->roles->pluck('id')->all()??[]))): echo 'checked'; endif; ?> class="mt-1 h-4 w-4"><span><strong class="block"><?php echo e($role->name); ?></strong><small class="text-slate-500"><?php echo e($role->description); ?></small></span></label><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></div></div>
        <div class="flex justify-end gap-3"><a href="<?php echo e(route('admin.users.index')); ?>" class="rounded-xl border px-5 py-3 font-bold">Cancel</a><button class="rounded-xl bg-slate-950 px-6 py-3 font-black text-white"><?php echo e($user?'Save Changes':'Create User'); ?></button></div>
    </form>
    <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($user): ?>
    <div class="rounded-3xl border border-red-100 bg-red-50/60 p-6"><h2 class="font-black text-red-800">Admin Password Reset</h2><p class="mt-1 text-sm text-red-700">The existing password can never be viewed. Set a new password instead.</p><form method="POST" action="<?php echo e(route('admin.users.reset-password',$user)); ?>" class="mt-4 grid gap-3 sm:grid-cols-3"><?php echo csrf_field(); ?> <?php echo method_field('PUT'); ?><input type="password" name="password" required placeholder="New password" class="rounded-xl border px-4 py-3"><input type="password" name="password_confirmation" required placeholder="Confirm password" class="rounded-xl border px-4 py-3"><label class="flex items-center gap-2 rounded-xl bg-white px-4"><input type="checkbox" name="force_password_change" value="1" checked> Force change</label><button class="rounded-xl bg-red-600 px-5 py-3 font-black text-white sm:col-span-3">Reset Password</button></form></div>
    <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH E:\Laravel Project\optimumbiomedical\resources\views/admin/users/form.blade.php ENDPATH**/ ?>