<?php $__env->startSection('content'); ?>
<?php $company = $company ?? \App\Models\CompanyInfo::query()->first(); ?>
<div class="bg-slate-50">
    <section class="bg-slate-950 text-white"><div class="mx-auto max-w-7xl px-5 py-14 sm:px-6 lg:px-8 lg:py-18"><p class="text-sm font-bold uppercase tracking-[.18em] text-cyan-300">Contact Us</p><h1 class="mt-3 text-3xl font-black sm:text-4xl">Let's discuss your biomedical requirement</h1><p class="mt-4 max-w-2xl text-slate-300">Send us a message and our team can follow up with the right information for your equipment or service needs.</p></div></section>
    <section class="mx-auto max-w-7xl px-5 py-12 sm:px-6 lg:px-8 lg:py-16">
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if(session('success')): ?><div class="mb-6 rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-sm font-bold text-emerald-700"><?php echo e(session('success')); ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($errors->any()): ?><div class="mb-6 rounded-2xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-700"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $errors->all(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $error): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><div><?php echo e($error); ?></div><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        <div class="grid gap-7 lg:grid-cols-[.75fr_1.25fr]">
            <aside class="rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200 sm:p-8"><h2 class="text-xl font-black text-slate-900">Contact information</h2><div class="mt-7 space-y-5"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($company?->phone): ?><a href="tel:<?php echo e($company->phone); ?>" class="flex gap-4 rounded-2xl bg-slate-50 p-4"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-cyan-100 text-cyan-700"><i class="fa-solid fa-phone"></i></span><span><small class="block text-xs font-bold uppercase tracking-wider text-slate-400">Phone</small><strong class="mt-1 block text-sm text-slate-800"><?php echo e($company->phone); ?></strong></span></a><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($company?->email): ?><a href="mailto:<?php echo e($company->email); ?>" class="flex gap-4 rounded-2xl bg-slate-50 p-4"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-indigo-100 text-indigo-700"><i class="fa-solid fa-envelope"></i></span><span><small class="block text-xs font-bold uppercase tracking-wider text-slate-400">Email</small><strong class="mt-1 block break-all text-sm text-slate-800"><?php echo e($company->email); ?></strong></span></a><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($company?->address): ?><div class="flex gap-4 rounded-2xl bg-slate-50 p-4"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-emerald-100 text-emerald-700"><i class="fa-solid fa-location-dot"></i></span><span><small class="block text-xs font-bold uppercase tracking-wider text-slate-400">Address</small><strong class="mt-1 block text-sm leading-6 text-slate-800"><?php echo e($company->address); ?></strong></span></div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></aside>
            <div class="rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200 sm:p-8"><h2 class="text-xl font-black text-slate-900">Send a message</h2><form method="POST" action="<?php echo e(route('contact.store')); ?>" class="mt-6 space-y-5"><?php echo csrf_field(); ?><div class="grid gap-5 sm:grid-cols-2"><label><span class="mb-2 block text-sm font-bold text-slate-700">Name *</span><input name="name" value="<?php echo e(old('name')); ?>" required maxlength="120" class="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-cyan-500 focus:ring-2 focus:ring-cyan-100"></label><label><span class="mb-2 block text-sm font-bold text-slate-700">Email *</span><input name="email" type="email" value="<?php echo e(old('email')); ?>" required maxlength="190" class="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-cyan-500 focus:ring-2 focus:ring-cyan-100"></label><label><span class="mb-2 block text-sm font-bold text-slate-700">Phone</span><input name="phone" value="<?php echo e(old('phone')); ?>" maxlength="50" class="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-cyan-500 focus:ring-2 focus:ring-cyan-100"></label><label><span class="mb-2 block text-sm font-bold text-slate-700">Subject</span><input name="subject" value="<?php echo e(old('subject')); ?>" maxlength="190" class="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-cyan-500 focus:ring-2 focus:ring-cyan-100"></label></div><label><span class="mb-2 block text-sm font-bold text-slate-700">Message *</span><textarea name="message" rows="7" required minlength="10" maxlength="5000" class="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-cyan-500 focus:ring-2 focus:ring-cyan-100"><?php echo e(old('message')); ?></textarea></label><div class="flex justify-end"><button class="rounded-xl bg-slate-950 px-6 py-3 text-sm font-black text-white shadow-lg transition hover:bg-indigo-600">Send Message <i class="fa-solid fa-paper-plane ml-2"></i></button></div></form></div>
        </div>
    </section>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH E:\Laravel Project\optimumbiomedical\resources\views/contact/index.blade.php ENDPATH**/ ?>