<?php $__env->startSection('content'); ?>
<div class="mx-auto max-w-6xl space-y-6">
    <div>
        <p class="text-sm font-black uppercase tracking-widest text-indigo-600">Settings / Products</p>
        <h1 class="text-3xl font-black text-slate-900 sm:text-4xl">Product Display Control</h1>
        <p class="mt-2 max-w-3xl text-sm leading-6 text-slate-500">এখান থেকে Home এবং Shop-এর product card-এর layout, image, information, badge, button, spacing, shadow, responsive columns এবং অন্যান্য visual style এক জায়গা থেকে নিয়ন্ত্রণ করুন।</p>
    </div>

    <form method="POST" action="<?php echo e(route('admin.settings.product-display.update')); ?>" class="space-y-6">
        <?php echo csrf_field(); ?>

        
        <section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
            <div class="mb-5 flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><i class="fa-solid fa-table-cells-large"></i></span><div><h2 class="font-black">1. Layout & Responsive</h2><p class="text-xs text-slate-500">কোন screen-এ কতটি product থাকবে এবং grid/list কেমন হবে।</p></div></div>
            <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <label><span class="mb-1.5 block text-sm font-bold">Layout</span><select name="layout" class="w-full rounded-xl border border-slate-200 px-4 py-3"><option value="grid" <?php if($settings['layout'] === 'grid'): echo 'selected'; endif; ?>>Grid</option><option value="list" <?php if($settings['layout'] === 'list'): echo 'selected'; endif; ?>>List</option></select></label>
                <label><span class="mb-1.5 block text-sm font-bold">Mobile Columns</span><select name="mobile_columns" class="w-full rounded-xl border border-slate-200 px-4 py-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = [1,2]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $v): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($v); ?>" <?php if((int)$settings['mobile_columns']===$v): echo 'selected'; endif; ?>><?php echo e($v); ?> Column</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></label>
                <label><span class="mb-1.5 block text-sm font-bold">Tablet Columns</span><select name="tablet_columns" class="w-full rounded-xl border border-slate-200 px-4 py-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = [2,3,4]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $v): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($v); ?>" <?php if((int)$settings['tablet_columns']===$v): echo 'selected'; endif; ?>><?php echo e($v); ?> Columns</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></label>
                <label><span class="mb-1.5 block text-sm font-bold">Desktop Columns</span><select name="desktop_columns" class="w-full rounded-xl border border-slate-200 px-4 py-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = [3,4,5,6]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $v): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($v); ?>" <?php if((int)$settings['desktop_columns']===$v): echo 'selected'; endif; ?>><?php echo e($v); ?> Columns</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></label>
                <label><span class="mb-1.5 block text-sm font-bold">Grid Gap</span><select name="gap" class="w-full rounded-xl border border-slate-200 px-4 py-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = [3,4,5,6,8]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $v): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($v); ?>" <?php if((int)$settings['gap']===$v): echo 'selected'; endif; ?>><?php echo e($v); ?></option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></label>
                <label><span class="mb-1.5 block text-sm font-bold">Card Padding</span><select name="card_padding" class="w-full rounded-xl border border-slate-200 px-4 py-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = [3,4,5,6]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $v): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($v); ?>" <?php if((int)$settings['card_padding']===$v): echo 'selected'; endif; ?>><?php echo e($v); ?></option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></label>
                <label><span class="mb-1.5 block text-sm font-bold">Text Alignment</span><select name="text_align" class="w-full rounded-xl border border-slate-200 px-4 py-3"><option value="left" <?php if($settings['text_align']==='left'): echo 'selected'; endif; ?>>Left</option><option value="center" <?php if($settings['text_align']==='center'): echo 'selected'; endif; ?>>Center</option></select></label>
            </div>
        </section>

        
        <section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
            <div class="mb-5 flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-sky-50 text-sky-600"><i class="fa-solid fa-credit-card"></i></span><div><h2 class="font-black">2. Card Style</h2><p class="text-xs text-slate-500">Border, radius, shadow এবং hover effect।</p></div></div>
            <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <label><span class="mb-1.5 block text-sm font-bold">Card Style</span><select name="card_style" class="w-full rounded-xl border border-slate-200 px-4 py-3"><option value="clean" <?php if($settings['card_style']==='clean'): echo 'selected'; endif; ?>>Clean</option><option value="bordered" <?php if($settings['card_style']==='bordered'): echo 'selected'; endif; ?>>Bold Border</option><option value="soft" <?php if($settings['card_style']==='soft'): echo 'selected'; endif; ?>>Soft</option><option value="glass" <?php if($settings['card_style']==='glass'): echo 'selected'; endif; ?>>Glass</option></select></label>
                <label><span class="mb-1.5 block text-sm font-bold">Border Radius</span><select name="card_radius" class="w-full rounded-xl border border-slate-200 px-4 py-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['none'=>'Square','lg'=>'Small','xl'=>'Medium','2xl'=>'Large','3xl'=>'Extra Large']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $v=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($v); ?>" <?php if($settings['card_radius']===$v): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></label>
                <label><span class="mb-1.5 block text-sm font-bold">Shadow</span><select name="card_shadow" class="w-full rounded-xl border border-slate-200 px-4 py-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['none','sm','md','lg','xl']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $v): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($v); ?>" <?php if($settings['card_shadow']===$v): echo 'selected'; endif; ?>><?php echo e(strtoupper($v)); ?></option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></label>
                <label><span class="mb-1.5 block text-sm font-bold">Hover Effect</span><select name="hover_effect" class="w-full rounded-xl border border-slate-200 px-4 py-3"><option value="none" <?php if($settings['hover_effect']==='none'): echo 'selected'; endif; ?>>None</option><option value="lift" <?php if($settings['hover_effect']==='lift'): echo 'selected'; endif; ?>>Lift</option><option value="zoom" <?php if($settings['hover_effect']==='zoom'): echo 'selected'; endif; ?>>Zoom</option><option value="lift-shadow" <?php if($settings['hover_effect']==='lift-shadow'): echo 'selected'; endif; ?>>Lift + Shadow</option></select></label>
            </div>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['card_border'=>'Show Card Border','image_zoom'=>'Image Hover Zoom']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
                <label class="mt-4 flex items-center justify-between rounded-2xl border border-slate-200 p-4"><span class="font-bold"><?php echo e($label); ?></span><span><input type="hidden" name="<?php echo e($key); ?>" value="0"><input type="checkbox" name="<?php echo e($key); ?>" value="1" <?php if($settings[$key] ?? false): echo 'checked'; endif; ?> class="h-5 w-5 rounded border-slate-300 text-indigo-600"></span></label>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
        </section>

        
        <section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
            <div class="mb-5 flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><i class="fa-solid fa-image"></i></span><div><h2 class="font-black">3. Product Image</h2><p class="text-xs text-slate-500">Image ratio, fit এবং background।</p></div></div>
            <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <label><span class="mb-1.5 block text-sm font-bold">Image Ratio</span><select name="image_ratio" class="w-full rounded-xl border border-slate-200 px-4 py-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['1/1'=>'Square 1:1','4/3'=>'Landscape 4:3','3/4'=>'Portrait 3:4','16/9'=>'Wide 16:9','auto'=>'Auto']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $v=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($v); ?>" <?php if($settings['image_ratio']===$v): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></label>
                <label><span class="mb-1.5 block text-sm font-bold">Image Fit</span><select name="image_fit" class="w-full rounded-xl border border-slate-200 px-4 py-3"><option value="cover" <?php if($settings['image_fit']==='cover'): echo 'selected'; endif; ?>>Cover</option><option value="contain" <?php if($settings['image_fit']==='contain'): echo 'selected'; endif; ?>>Contain</option></select></label>
                <label><span class="mb-1.5 block text-sm font-bold">Image Background</span><select name="image_background" class="w-full rounded-xl border border-slate-200 px-4 py-3"><option value="slate" <?php if($settings['image_background']==='slate'): echo 'selected'; endif; ?>>Light Gray</option><option value="white" <?php if($settings['image_background']==='white'): echo 'selected'; endif; ?>>White</option><option value="transparent" <?php if($settings['image_background']==='transparent'): echo 'selected'; endif; ?>>Transparent</option></select></label>
            </div>
        </section>

        
        <?php
            $toggles = [
                'show_image'=>'Product Image','show_category'=>'Category','show_brand'=>'Brand','show_sku'=>'SKU','show_description'=>'Short Description','show_price'=>'Price','show_regular_price'=>'Regular Price','show_rating'=>'Rating','show_stock'=>'Stock Status','show_stock_quantity'=>'Stock Quantity','show_discount_badge'=>'Discount Badge','show_new_badge'=>'NEW Badge','show_featured_badge'=>'Featured Badge','show_wishlist'=>'Wishlist','show_view_button'=>'View Product','show_add_to_cart'=>'Add to Cart',
            ];
        ?>
        <section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
            <div class="mb-5 flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-600"><i class="fa-solid fa-list-check"></i></span><div><h2 class="font-black">4. What Will Be Shown</h2><p class="text-xs text-slate-500">Product card-এ কোন তথ্য/element দেখাবেন তা checkbox দিয়ে ঠিক করুন।</p></div></div>
            <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = $toggles; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
                    <label class="flex cursor-pointer items-center justify-between rounded-2xl border border-slate-200 p-4 transition hover:border-indigo-200 hover:bg-indigo-50/30"><span class="font-bold text-slate-700"><?php echo e($label); ?></span><span><input type="hidden" name="<?php echo e($key); ?>" value="0"><input type="checkbox" name="<?php echo e($key); ?>" value="1" <?php if($settings[$key] ?? false): echo 'checked'; endif; ?> class="h-5 w-5 rounded border-slate-300 text-indigo-600"></span></label>
                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
            </div>
            <div class="mt-4 grid gap-4 sm:grid-cols-3">
                <label><span class="mb-1.5 block text-sm font-bold">Product Name Lines</span><select name="name_lines" class="w-full rounded-xl border border-slate-200 px-4 py-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = [1,2,3]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $v): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($v); ?>" <?php if((int)$settings['name_lines']===$v): echo 'selected'; endif; ?>><?php echo e($v); ?> Line</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></label>
                <label><span class="mb-1.5 block text-sm font-bold">Description Lines</span><select name="description_lines" class="w-full rounded-xl border border-slate-200 px-4 py-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = [1,2,3]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $v): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($v); ?>" <?php if((int)$settings['description_lines']===$v): echo 'selected'; endif; ?>><?php echo e($v); ?> Lines</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></label>
                <label><span class="mb-1.5 block text-sm font-bold">Price Size</span><select name="price_size" class="w-full rounded-xl border border-slate-200 px-4 py-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['sm'=>'Small','lg'=>'Large','xl'=>'Extra Large','2xl'=>'2X Large']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $v=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($v); ?>" <?php if($settings['price_size']===$v): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></label>
                <label><span class="mb-1.5 block text-sm font-bold">Price Decimals</span><select name="price_decimals" class="w-full rounded-xl border border-slate-200 px-4 py-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = [0,1,2]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $v): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($v); ?>" <?php if((int)$settings['price_decimals']===$v): echo 'selected'; endif; ?>><?php echo e($v); ?> decimal</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></label>
                <label><span class="mb-1.5 block text-sm font-bold">Currency Position</span><select name="currency_position" class="w-full rounded-xl border border-slate-200 px-4 py-3"><option value="before" <?php if($settings['currency_position']==='before'): echo 'selected'; endif; ?>>Before price</option><option value="after" <?php if($settings['currency_position']==='after'): echo 'selected'; endif; ?>>After price</option></select></label>
            </div>
        </section>

        
        <section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
            <div class="mb-5 flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-600"><i class="fa-solid fa-hand-pointer"></i></span><div><h2 class="font-black">5. Button Style</h2><p class="text-xs text-slate-500">Action button-এর appearance এবং width।</p></div></div>
            <div class="grid gap-4 sm:grid-cols-2">
                <label><span class="mb-1.5 block text-sm font-bold">Button Style</span><select name="button_style" class="w-full rounded-xl border border-slate-200 px-4 py-3"><option value="solid" <?php if($settings['button_style']==='solid'): echo 'selected'; endif; ?>>Solid</option><option value="outline" <?php if($settings['button_style']==='outline'): echo 'selected'; endif; ?>>Outline</option><option value="soft" <?php if($settings['button_style']==='soft'): echo 'selected'; endif; ?>>Soft</option></select></label>
                <label class="flex items-center justify-between rounded-2xl border border-slate-200 p-4"><span class="font-bold">Full Width Buttons</span><span><input type="hidden" name="button_full_width" value="0"><input type="checkbox" name="button_full_width" value="1" <?php if($settings['button_full_width'] ?? false): echo 'checked'; endif; ?> class="h-5 w-5 rounded border-slate-300 text-indigo-600"></span></label>
                <label><span class="mb-1.5 block text-sm font-bold">Button Layout</span><select name="button_layout" class="w-full rounded-xl border border-slate-200 px-4 py-3"><option value="row" <?php if($settings['button_layout']==='row'): echo 'selected'; endif; ?>>Inline / Row</option><option value="stack" <?php if($settings['button_layout']==='stack'): echo 'selected'; endif; ?>>Stacked</option></select></label>
            </div>
        </section>

        
        <section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
            <div class="mb-5 flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-rose-50 text-rose-600"><i class="fa-solid fa-location-dot"></i></span><div><h2 class="font-black">6. কোথায় Product দেখাবে</h2><p class="text-xs text-slate-500">একই product card design Home এবং Shop উভয় জায়গায় ব্যবহার হবে।</p></div></div>
            <div class="grid gap-3 sm:grid-cols-2">
                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = ['show_home_products'=>'Home Page Product Section','show_shop_products'=>'Shop Page Product Section']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?>
                    <label class="flex items-center justify-between rounded-2xl border border-slate-200 p-4"><span class="font-bold"><?php echo e($label); ?></span><span><input type="hidden" name="<?php echo e($key); ?>" value="0"><input type="checkbox" name="<?php echo e($key); ?>" value="1" <?php if($settings[$key] ?? false): echo 'checked'; endif; ?> class="h-5 w-5 rounded border-slate-300 text-indigo-600"></span></label>
                <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?>
            </div>
            <div class="mt-4 grid gap-4 sm:grid-cols-3">
                <label class="sm:col-span-2"><span class="mb-1.5 block text-sm font-bold">Home Product Section Title</span><input name="home_title" value="<?php echo e(old('home_title', $settings['home_title'])); ?>" class="w-full rounded-xl border border-slate-200 px-4 py-3"></label>
                <label><span class="mb-1.5 block text-sm font-bold">Home Product Limit</span><input type="number" min="1" max="24" name="home_limit" value="<?php echo e(old('home_limit', $settings['home_limit'])); ?>" class="w-full rounded-xl border border-slate-200 px-4 py-3"></label>
                <label><span class="mb-1.5 block text-sm font-bold">Home Desktop Columns</span><select name="home_desktop_columns" class="w-full rounded-xl border border-slate-200 px-4 py-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::openLoop(); ?><?php endif; ?><?php $__currentLoopData = [2,3,4,5,6]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $v): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::startLoopIteration(); ?><?php endif; ?><option value="<?php echo e($v); ?>" <?php if((int)$settings['home_desktop_columns']===$v): echo 'selected'; endif; ?>><?php echo e($v); ?> Columns</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::endLoop(); ?><?php endif; ?><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php \Livewire\Features\SupportCompiledWireKeys\SupportCompiledWireKeys::closeLoop(); ?><?php endif; ?></select></label>
            </div>
        </section>

        <div class="sticky bottom-3 z-10 flex justify-end rounded-2xl border border-slate-200 bg-white/95 p-3 shadow-xl backdrop-blur">
            <button class="rounded-xl bg-gradient-to-r from-indigo-600 to-sky-500 px-7 py-3 text-sm font-black text-white shadow-lg shadow-indigo-200 transition hover:-translate-y-0.5">Save All Product Display Settings</button>
        </div>
    </form>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH E:\Laravel Project\optimumbiomedical\resources\views/admin/settings/product-display.blade.php ENDPATH**/ ?>