@extends('layouts.admin')
@section('content')
<div class="mx-auto max-w-7xl space-y-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div>
            <p class="text-sm font-black uppercase tracking-widest text-indigo-600">Settings / Services</p>
            <h1 class="text-3xl font-black text-slate-900">Service Management</h1>
            <p class="mt-1 text-sm text-slate-500">Manage hospital biomedical and other services shown on the website.</p></div><a href="{{ route('admin.settings.services.create', ['type' => $type]) }}" class="inline-flex items-center justify-center rounded-xl bg-indigo-600 px-5 py-3 text-sm font-black text-white shadow hover:bg-indigo-700"><i class="fa-solid fa-plus mr-2"></i>Add Service</a></div>
    @if(session('success'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ session('success') }}</div>@endif
    <div class="flex flex-wrap gap-2"><a href="{{ route('admin.settings.services.index', ['type'=>'hospital']) }}" class="rounded-xl px-4 py-2 text-sm font-bold {{ $type==='hospital'?'bg-slate-900 text-white':'bg-white text-slate-600 ring-1 ring-slate-200' }}">Hospital Services</a><a href="{{ route('admin.settings.services.index', ['type'=>'other']) }}" class="rounded-xl px-4 py-2 text-sm font-bold {{ $type==='other'?'bg-slate-900 text-white':'bg-white text-slate-600 ring-1 ring-slate-200' }}">Other Services</a></div>
    <div class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
        <div class="admin-table-wrap"><table class="w-full text-left"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-4">Service</th><th class="px-5 py-4">Type</th><th class="px-5 py-4">Order</th><th class="px-5 py-4">Status</th><th class="px-5 py-4 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">
        @forelse($services->where('service_type',$type) as $service)<tr><td class="px-5 py-4"><div class="flex items-center gap-3"><div class="h-14 w-20 overflow-hidden rounded-xl bg-slate-100">@if($service->image_path)<img src="{{ asset($service->image_path) }}" class="h-full w-full object-cover" alt="">@else<span class="grid h-full place-items-center text-indigo-500"><i class="fa-solid {{ $service->icon ?: 'fa-briefcase-medical' }}"></i></span>@endif</div><div><p class="font-black text-slate-900">{{ $service->title }}</p><p class="mt-1 max-w-md text-xs text-slate-500">{{ $service->short_description }}</p></div></div></td><td class="px-5 py-4 text-sm text-slate-600">{{ $service->service_type === 'hospital' ? 'Hospital' : 'Other' }}</td><td class="px-5 py-4 text-sm font-bold text-slate-600">{{ $service->sort_order }}</td><td class="px-5 py-4"><span class="rounded-full px-3 py-1 text-xs font-bold {{ $service->status?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500' }}">{{ $service->status?'Active':'Hidden' }}</span></td><td class="px-5 py-4"><div class="flex justify-end gap-2"><a href="{{ route('admin.settings.services.edit',$service) }}" class="grid h-9 w-9 place-items-center rounded-lg bg-indigo-50 text-indigo-600" title="Edit"><i class="fa-solid fa-pen"></i></a><form method="POST" action="{{ route('admin.settings.services.status',$service) }}">@csrf @method('PATCH')<button class="grid h-9 w-9 place-items-center rounded-lg bg-amber-50 text-amber-600" title="Toggle status"><i class="fa-solid fa-eye"></i></button></form><form method="POST" action="{{ route('admin.settings.services.delete',$service) }}" onsubmit="return confirm('Delete this service?')">@csrf @method('DELETE')<button class="grid h-9 w-9 place-items-center rounded-lg bg-red-50 text-red-600" title="Delete"><i class="fa-solid fa-trash"></i></button></form></div></td></tr>
        @empty<tr><td colspan="5" class="px-5 py-12 text-center text-sm text-slate-500">No services found.</td></tr>@endforelse
        </tbody></table></div>
    </div>
</div>
@endsection
