@extends('layouts.admin')
@section('content')
<div class="mx-auto max-w-7xl space-y-6"><div><p class="text-sm font-bold uppercase tracking-widest text-indigo-600">Catalog</p><h1 class="text-3xl font-black">Categories · Subcategories · Brands</h1><p class="mt-1 text-sm text-slate-500">Manage the same catalog hierarchy used by your storefront.</p></div>
<div class="grid gap-5 lg:grid-cols-3">
<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-black">Add Category</h2><form method="POST" action="{{ url('/admin/catalog/categories') }}" enctype="multipart/form-data" class="mt-4 space-y-3">@csrf<input name="category_name" required placeholder="Category name" class="w-full rounded-xl border border-slate-200 px-4 py-3"><input type="file" name="category_image" accept="image/*" class="w-full rounded-xl border border-slate-200 p-3"><button class="w-full rounded-xl bg-slate-950 py-3 font-black text-white transition hover:bg-indigo-700">Add Category</button></form></div>
<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-black">Add Subcategory</h2><form method="POST" action="{{ url('/admin/catalog/subcategories') }}" class="mt-4 space-y-3">@csrf<select name="category_id" required class="w-full rounded-xl border border-slate-200 px-4 py-3"><option value="">Select category</option>@foreach($categories as $c)<option value="{{ $c->category_id }}">{{ $c->category_name }}</option>@endforeach</select><select name="parent_subcategory_id" class="w-full rounded-xl border border-slate-200 px-4 py-3"><option value="">No parent (top-level subcategory)</option>@foreach($subcategories as $s)<option value="{{ $s->subcategory_id }}">{{ $s->category?->category_name }} → {{ $s->subcategory_name }}</option>@endforeach</select><input name="subcategory_name" required placeholder="Subcategory name" class="w-full rounded-xl border border-slate-200 px-4 py-3"><p class="text-xs text-slate-500">Choose a parent to create another nested level. This can be repeated as many times as needed.</p><button class="w-full rounded-xl bg-slate-950 py-3 font-black text-white transition hover:bg-cyan-700">Add Subcategory</button></form></div>
<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-black">Add Brand</h2><form method="POST" action="{{ url('/admin/catalog/brands') }}" class="mt-4 space-y-3">@csrf<select name="subcategory_id" required class="w-full rounded-xl border border-slate-200 px-4 py-3"><option value="">Select subcategory</option>@foreach($subcategories as $s)<option value="{{ $s->subcategory_id }}">{{ $s->subcategory_name }} · {{ $s->category?->category_name }}</option>@endforeach</select><input name="brand_name" required placeholder="Brand name" class="w-full rounded-xl border border-slate-200 px-4 py-3"><button class="w-full rounded-xl bg-slate-950 py-3 font-black text-white transition hover:bg-indigo-700">Add Brand</button></form></div>
</div>
<div class="grid gap-5 xl:grid-cols-3">
<section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b p-5"><h2 class="font-black">Categories</h2></div><div class="divide-y">@forelse($categories as $c)<div class="flex items-center justify-between gap-3 p-4"><div class="flex items-center gap-3">@if($c->category_image)<img src="{{ asset($c->category_image) }}" class="h-10 w-10 rounded-lg object-cover">@else<span class="grid h-10 w-10 place-items-center rounded-lg bg-slate-100 text-slate-400"><i class="fa-solid fa-folder"></i></span>@endif<div><div class="font-bold">{{ $c->category_name }}</div><div class="text-xs text-slate-500">{{ $c->products_count }} products</div></div></div><form method="POST" action="{{ url('/admin/catalog/categories/'.$c->category_id) }}" onsubmit="return confirm('Delete category?')">@csrf @method('DELETE')<button class="text-xs font-bold text-red-600 hover:underline">Delete</button></form></div>@empty<div class="p-8 text-center text-sm text-slate-500">No categories.</div>@endforelse</div></section>
<section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b p-5"><h2 class="font-black">Subcategories</h2></div><div class="divide-y">@forelse($subcategories as $s)<div class="flex items-center justify-between gap-3 p-4"><div><div class="font-bold">{{ $s->subcategory_name }}</div><div class="text-xs text-slate-500">{{ $s->category?->category_name ?? '—' }}</div></div><form method="POST" action="{{ url('/admin/catalog/subcategories/'.$s->subcategory_id) }}" onsubmit="return confirm('Delete subcategory?')">@csrf @method('DELETE')<button class="text-xs font-bold text-red-600 hover:underline">Delete</button></form></div>@empty<div class="p-8 text-center text-sm text-slate-500">No subcategories.</div>@endforelse</div></section>
<section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b p-5"><h2 class="font-black">Brands</h2></div><div class="divide-y">@forelse($brands as $b)<div class="flex items-center justify-between gap-3 p-4"><div><div class="font-bold">{{ $b->brand_name }}</div><div class="text-xs text-slate-500">{{ $b->brand_name }}</div><div class="text-xs text-slate-500">{{ $b->subcategory?->subcategory_name ?? '—' }} · {{ $b->subcategory?->category?->category_name ?? '—' }}</div></div><form method="POST" action="{{ url('/admin/catalog/brands/'.$b->brand_id) }}" onsubmit="return confirm('Delete brand?')">@csrf @method('DELETE')<button class="text-xs font-bold text-red-600 hover:underline">Delete</button></form></div>@empty<div class="p-8 text-center text-sm text-slate-500">No brands.</div>@endforelse</div></section>
</div></div>
@endsection
